# Generated by Django 5.2.14 on 2026-07-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0014_teamlogsconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsview",
            name="columns",
            field=models.JSONField(default=None, null=True),
        ),
    ]
