# Generated by Django 5.2.15 on 2026-07-01 15:26

import django.db.models.deletion
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1247_oauthaccesstoken_token_idx"),
        ("workflows", "0008_teamworkflowsconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hogflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailReputationState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("workflow", "Workflow"), ("team", "Team")],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warned", "Warned"),
                            ("paused", "Paused"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("bounce_rate", models.FloatField(default=0.0)),
                ("complaint_rate", models.FloatField(default=0.0)),
                ("emails_sent", models.BigIntegerField(default=0)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("state_changed_at", models.DateTimeField(blank=True, null=True)),
                ("warned_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pause_reason",
                    models.CharField(
                        blank=True,
                        choices=[("bounce", "Bounce"), ("complaint", "Complaint")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "previous_flow_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hog_flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.hogflow",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "db_table": "posthog_emailreputationstate",
                "indexes": [models.Index(fields=["team", "state"], name="posthog_ema_team_id_527d9d_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("hog_flow__isnull", False)),
                        fields=("team", "hog_flow"),
                        name="unique_workflow_reputation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("hog_flow__isnull", True)),
                        fields=("team",),
                        name="unique_team_reputation",
                    ),
                ],
            },
        ),
    ]
